### ISSUE TITLE
Heroku deploy error

### ISSUE THREAD

**Issue by STRIXVERDEN** [lorien/sbin#3]
```
-----> Python app detected

-----> Installing python-2.7.12

     $ pip install -r requirements.txt

       Collecting bottle==0.12.9 (from -r requirements.txt (line 1))

         Downloading bottle-0.12.9.tar.gz (69kB)

       Collecting python-baseconv==1.1.3 (from -r requirements.txt (line 2))

         Downloading python-baseconv-1.1.3.tar.gz

       Collecting peewee==2.8.5 (from -r requirements.txt (line 3))

         Downloading peewee-2.8.5.tar.gz (506kB)

       Collecting gunicorn==19.6.0 (from -r requirements.txt (line 4))

         Downloading gunicorn-19.6.0-py2.py3-none-any.whl (114kB)

       Installing collected packages: bottle, python-baseconv, peewee, gunicorn

         Running setup.py install for bottle: started

           Running setup.py install for bottle: finished with status 'done'

         Running setup.py install for python-baseconv: started

           Running setup.py install for python-baseconv: finished with status 'done'

         Running setup.py install for peewee: started

           Running setup.py install for peewee: finished with status 'done'

       Successfully installed bottle-0.12.9 gunicorn-19.6.0 peewee-2.8.5 python-baseconv-1.1.3

-----> Running post-compile hook

INFO:root:Start migration

Traceback (most recent call last):

  File "migrate.py", line 88, in <module>

    main()

  File "migrate.py", line 76, in main

    step1()

TypeError: step1() takes exactly 1 argument (0 given)

 !     Push rejected, failed to compile Python app.

 !     Push failed
```

**Comment by lorien** [comment]
Yep. I've fixed few bugs. Check out the latest commit.
